version: 1.0
task: 1
num_classes: 2

classes: ["background", "building"]
data_ratio: 1.0
class_to_color:
  "background": 0
  "building": 255

imagesize: 500

train:
  batchsize: 16
  shuffle: True
validation:
  batchsize: 16
  shuffle: False
task1:
  batchsize: 16
  shuffle: False
task2:
  batchsize: 16
  shuffle: False